[package]
name = "tg-online-keeper"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
fastrand = "2.0.1"
futures-util = "0.3.30"
grammers-client = "0.5.0"
grammers-session = "0.5.1"
grammers-tl-types = "0.5.1"
tokio = { version = "1.36.0" }
